teleop_twist_joy_node:
  ros__parameters:
    # Linear movement (omnidirectional for mecanum)
    axis_linear:
      x: 1    # Left stick Y - forward/backward
      y: 0    # Left stick X - strafe left/right
    scale_linear:
      x: 5.0  # INCREASED from 0.5 to 1.0 (2x faster)
      y: 5.0  # INCREASED from 0.5 to 1.0 (2x faster)
    scale_linear_turbo:
      x: 10.0  # INCREASED from 1.0 to 2.0 (4x faster with turbo)
      y: 10.0  # INCREASED from 1.0 to 2.0 (4x faster with turbo)

    # Angular movement  
    axis_angular:
      yaw: 2  # Right stick X - rotation
    scale_angular:
      yaw: 5.0  # INCREASED from 0.4 to 1.0 (2.5x faster rotation)
    scale_angular_turbo:
      yaw: 10.0  # INCREASED from 0.8 to 2.0 (2.5x faster rotation with turbo)

    require_enable_button: true
    enable_button: 4  # L1 button (deadman switch)
    enable_turbo_button: 5  # R1 button (turbo mode - HOLD for extra speed!)