controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    
    # Controllers to load and start
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint

# FIXED: Updated Mecanum Drive Controller Configuration with new parameter names
mecanum_drive_controller:
  ros__parameters:
    # Reference timeout - after which commands are reset for safety
    reference_timeout: 0.5
    
    # UPDATED: Joint names using new parameter structure
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    
    # Kinematics parameters (from your robot's physical dimensions)
    kinematics:
      base_frame_offset:
        x: 0.0
        y: 0.0 
        theta: 0.0
      wheels_radius: 0.04  # 40mm radius wheels
      sum_of_robot_center_projection_on_X_Y_axis: 0.329  # lx + ly = 0.16 + 0.169 = 0.329
    
    # Frame IDs
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    
    # Publishing options
    enable_odom_tf: true
    
    # Covariance matrices (6x6 diagonal values: x, y, z, roll, pitch, yaw)
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    
    # Safety - timeout for cmd_vel commands
    cmd_vel_timeout: 0.5
    use_stamped_vel: false