# SLAM Configuration for Yahboom Robot with ZED2i
# File: src/robot_bringup/config/slam_params.yaml

slam_toolbox:
  ros__parameters:
    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_map_saver: true
    use_sim_time: false
    
    # SLAM Configuration
    mode: mapping # Can be: mapping, localization, or lifelong
    
    # Map saving (don't load existing map for new SLAM session)
    # map_file_name: /tmp/slam_map  # Commented out to avoid loading non-existent map
    map_start_at_dock: true
    
    # Solver Parameters
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    
    # SLAM Algorithm Parameters
    
    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_time_interval: 0.1  # seconds between processing scans (faster processing)
    transform_publish_period: 0.05  # 20hz transform publishing (slower)
    map_update_interval: 2.0  # seconds between map updates (faster updates)
    resolution: 0.05  # meters per pixel
    max_laser_range: 12.0  # meters (ZED2i depth range)
    minimum_travel_distance: 0.5  # meters before processing new scan
    minimum_travel_heading: 0.5  # radians before processing new scan
    scan_buffer_size: 100  # Much larger buffer to handle high-frequency messages
    scan_buffer_maximum_scan_distance: 10.0
    
    # Transform timeout and tolerance settings
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
    
    # Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
    
    # Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03
    
    # Scan Matcher Parameters
    distance_variance_penalty: 0.5
    angular_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349  # 0.2 degrees
    coarse_search_angle_offset: 0.349   # 20 degrees
    coarse_angle_resolution: 0.0349     # 2 degrees
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true