# ZED2i VI-SLAM Configuration
# Phase 1: Basic positional tracking and TF setup
# File: src/robot_bringup/config/zed_vi_slam_config.yaml

/**:
  ros__parameters:
    # General parameters
    general:
      camera_model: 'zed2i'
      camera_name: 'zed2i'
      grab_resolution: 'HD720'    # Good balance of quality vs performance on Jetson
      grab_frame_rate: 30
      
    # Position tracking parameters - ENABLED FOR VI-SLAM
    pos_tracking:
      pos_tracking_enabled: true
      publish_tf: true            # ZED publishes TF transforms for VI-SLAM
      publish_map_tf: true        # ZED publishes map->odom transform
      map_frame: 'map'
      odometry_frame: 'odom'
      base_frame: 'zed2i_camera_link'  # ZED tracks camera frame - publishes odom->camera_link
      
      # Override any default base frame settings
      camera_frame: 'zed2i_camera_center'  # ZED camera center frame
      
      # Coordinate system setup  
      initial_world_transform: [0,0,0, 0,0,0]  # [x,y,z, roll,pitch,yaw] initial pose
      set_gravity_as_origin: true              # Use gravity to establish world frame
      set_floor_as_origin: false               # Don't assume floor level
      
      # Camera offset from base_link (camera is 8cm forward, 6.5cm up from base_link)
      # This tells ZED where it is mounted relative to the robot base
      transform_time_offset: 0.0
      
      # VI-SLAM quality settings
      depth_min_range: 0.3        # 30cm minimum depth
      imu_fusion: true            # Enable IMU fusion for VI-SLAM
      
      # Area memory for relocalization (disabled initially for Phase 1)
      area_memory: false
      area_memory_db_path: ""
      
    # Depth parameters optimized for navigation
    depth:
      min_depth: 0.3
      max_depth: 10.0
      depth_mode: 'ULTRA'         # Best quality for VI-SLAM
      depth_stabilization: 1      # Reduce noise (0=disabled, 1=enabled)
      openni_depth_mode: false
      
    # Sensors configuration
    sensors:
      publish_imu_tf: true        # Publish IMU transform
      sensors_timestamp_sync: false  # Keep simple for now
      
    # Video parameters optimized for Jetson performance  
    video:
      brightness: 4
      contrast: 4
      hue: 0
      saturation: 4
      sharpness: 4
      gamma: 8
      auto_exposure_gain: true
      exposure: 100
      gain: 100
      auto_whitebalance: true
      whitebalance_temperature: 42
      
    # Object detection disabled for performance
    od:
      od_enabled: false
      
    # Body tracking disabled for performance  
    bt:
      bt_enabled: false
      
    # Spatial mapping for Phase 4 (disabled for Phase 1)
    mapping:
      mapping_enabled: false
      resolution: 0.05
      max_mapping_range: 15.0
      fused_point_cloud_freq: 1.0