# ZED2i Navigation Configuration - Industry Standard  
# Phase: NAVIGATION MODE (Optimized for nav2 stack integration)
# File: src/robot_bringup/config/zed_navigation_config.yaml

/**:
  ros__parameters:
    # General parameters - optimized for navigation performance
    general:
      camera_model: 'zed2i'
      camera_name: 'zed2i'
      grab_resolution: 'VGA'      # Lower resolution for nav2 performance
      grab_frame_rate: 15         # Reduced frame rate for navigation
      
    # Position tracking parameters - NAVIGATION MODE
    pos_tracking:
      pos_tracking_enabled: true
      publish_tf: true            # ZED publishes TF transforms for navigation
      publish_map_tf: true        # ZED publishes map->odom transform
      map_frame: 'map'
      odometry_frame: 'odom'
      base_frame: 'zed2i_camera_link'  # ZED tracks camera frame
      
      # Camera frame reference
      camera_frame: 'zed2i_camera_center'
      
      # Navigation coordinate system - use existing map
      initial_world_transform: [0,0,0, 0,0,0]  # Will be overridden by area memory
      set_gravity_as_origin: true              # Consistent with mapping
      set_floor_as_origin: false
      
      # Navigation quality settings - balance accuracy vs performance
      depth_min_range: 0.3        # 30cm minimum depth
      imu_fusion: true            # Enable IMU fusion for stable odometry
      
      # NAVIGATION MODE: ENABLE AREA MEMORY for relocalization
      area_memory: true
      area_memory_db_path: "/tmp/zed_area_memory.area"  # Load existing map
      
    # Depth parameters - optimized for obstacle detection
    depth:
      min_depth: 0.2              # Closer detection for obstacles
      max_depth: 8.0              # Shorter range for nav2 efficiency
      depth_mode: 'PERFORMANCE'   # Fast depth for real-time navigation
      depth_stabilization: 1      # Reduce noise for obstacle detection
      openni_depth_mode: false
      
    # Sensors configuration
    sensors:
      publish_imu_tf: true        # Important for navigation odometry
      sensors_timestamp_sync: false
      
    # Video parameters optimized for navigation performance  
    video:
      brightness: 4
      contrast: 4
      hue: 0
      saturation: 3               # Slightly reduced for performance
      sharpness: 3                # Slightly reduced for performance
      gamma: 8
      auto_exposure_gain: true
      exposure: 100
      gain: 100
      auto_whitebalance: true
      whitebalance_temperature: 42
      
    # Object detection disabled for navigation performance
    od:
      od_enabled: false
      
    # Body tracking disabled for navigation performance  
    bt:
      bt_enabled: false
      
    # Spatial mapping - DISABLED for navigation (use existing map)
    mapping:
      mapping_enabled: false      # No mapping during navigation
      resolution: 0.05            # Keep consistent (not used)
      max_mapping_range: 8.0      # Reduced range (not used)
      fused_point_cloud_freq: 0.0 # Disable fused cloud (not needed for nav2)
      
      # Navigation-specific parameters
      map_publish_freq: 0.0       # Disable map publishing (use existing)
      save_map_on_shutdown: false # Don't save during navigation